import { BsClipboard } from 'react-icons/bs';

const Components = () => {
  return (
    <div className="flex flex-col lg:flex-row items-center gap-4 px-6 lg:px-0 w-full lg:w-[90%] mx-auto my-12 lg:my-36">
      <div className="w-full lg:w-1/2 flex flex-col gap-4 items-start">
        <div className="flex gap-4">
          <div className="bg-[#dc3545]/10 text-[#dc3545] p-4 rounded-xl flex ">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              className="w-10 h-10"
              viewBox="0 0 16 16"
            >
              <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v2A1.5 1.5 0 0 0 1.5 5h13A1.5 1.5 0 0 0 16 3.5v-2A1.5 1.5 0 0 0 14.5 0h-13zm1 2h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1zm9.927.427A.25.25 0 0 1 12.604 2h.792a.25.25 0 0 1 .177.427l-.396.396a.25.25 0 0 1-.354 0l-.396-.396zM0 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8zm1 3v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2H1zm14-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2h14zM2 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
            </svg>
          </div>

          <div className="flex items-center text-3xl text-gray-500">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
          </div>
          <div className="bg-[#0dcaf0]/10 text-[#0dcaf0] p-4 rounded-xl flex ">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              className="w-10 h-10"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M1.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C2.25 2 1.49 2.759 1.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6ZM14.886 7.9v.164c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456v-1.3c-1.114 0-1.49-.362-1.49-1.456V4.352C14.51 2.759 13.75 2 12.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6ZM7.5 11.5V9.207l-1.621 1.621-.707-.707L6.792 8.5H4.5v-1h2.293L5.172 5.879l.707-.707L7.5 6.792V4.5h1v2.293l1.621-1.621.707.707L9.208 7.5H11.5v1H9.207l1.621 1.621-.707.707L8.5 9.208V11.5h-1Z"
              />
            </svg>
          </div>
        </div>
        <h1 className="section-h1 font-semibold leading-[1.2]">
          Components, meet the <br />
          Utility API
        </h1>
        <p className=" text-[1rem] md:text-lg lg:text-xl w-full">
          New in Bootstrap 5, our utilities are now generated by our{' '}
          <span className="text-blue-600 underline inline-block hover:text-blue-800 cursor-pointer">
            Utility API
          </span>
          . We built it as a feature-packed Sass map that can be quickly and
          easily customized. It's never been easier to add, remove, or modify
          any utility classes. Make utilities responsive, add pseudo-class
          variants, and give them custom names.
        </p>
        <span className="flex items-center text-blue-600 font-medium cursor-pointer text-[1rem] md:text-lg lg:text-xl pb-2 hover:text-blue-800 peer">
          <span className="border-b-2 border-blue-400">
            Learn more about utilities{' '}
          </span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M13 7l5 5m0 0l-5 5m5-5H6"
            />
          </svg>
        </span>
        <span className="flex items-center text-blue-600 font-medium cursor-pointer text-[1rem] md:text-lg lg:text-xl pb-2 hover:text-blue-800 peer">
          <span className="border-b-2 border-blue-400">
            Explore customized components{' '}
          </span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M13 7l5 5m0 0l-5 5m5-5H6"
            />
          </svg>
        </span>
      </div>
      <div className="w-full lg:w-1/2 flex flex-col gap-4 items-start">
        <div className="w-full relative z-[1] p-4 py-5 rounded bg-[#f8f9fa] flex items-center justify-start gap-2 text-center pr-16 text-sm">
          <pre className="overflow-auto">
            <code className="text-left language-css flex flex-col">
              <span className="text-gray-500">
                &#47;&#47; Create and extend utilities with the Utility API
              </span>
              <br />
              <span>
                <span className="import">@import</span>{' '}
                <span className="blue">"bootstrap/scss/bootstrap"</span>;
              </span>
              <br />
              <span className="pl-4 ">
                <span className="orange">$utilities</span>:
                <span className="blue"> map-merge</span>(
              </span>
              <span className="pl-8">
                <span className="orange">$utilities</span>,
              </span>
              <span className="pl-8">(</span>
              <span className="pl-12">
                <span className="blue">"cursor"</span>: (
              </span>
              <span className="pl-16">
                <span className="purple">property</span>:
                <span className="orange">cursor</span>,
              </span>
              <span className="pl-16">
                <span className="purple">class</span>:
                <span className="orange">cursor</span>,
              </span>
              <span className="pl-16">
                <span className="purple">responsive</span>:
                <span className="orange">true</span>,
              </span>
              <span className="pl-16">
                <span className="purple">values</span>:
                <span className="orange">auto pointer grab</span>,
              </span>
              <span className="pl-12">)</span>
              <span className="pl-8">)</span>
              <span className="pl-4">);</span>
            </code>
          </pre>

          <span
            className="absolute top-[18px] hidden md:block right-5"
            onClick={() =>
              navigator.clipboard
                .writeText(`// Create and extend utilities with the Utility API

@import "bootstrap/scss/bootstrap";

$utilities: map-merge(
  $utilities,
  (
    "cursor": (
      property: cursor,
      class: cursor,
      responsive: true,
      values: auto pointer grab,
    )
  )
);`)
            }
          >
            <BsClipboard className="cursor-pointer hover:text-[#0d6efd] text-lg" />
          </span>
        </div>
      </div>
    </div>
  );
};

export default Components;
